version: "3"
services:
  auth-db:
    image: postgres
    restart: always
    container_name: auth-db
    environment:
      POSTGRES_USER: "auth"
      POSTGRES_DB: "auth"
      POSTGRES_PASSWORD: "123456"
    ports:
      - "15460:5432"
#    networks:
#      - shared_network
#        
#networks:
#  shared_network:
#    external: true